# -*- coding: utf-8 -*-
"""NLP_basic_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awY6V_Ne9Dkm_2IVVmtOHcsAqiOzwpLP
"""

from google.colab import drive
drive.mount('/content/drive')

# 1. Imports

import pandas as pd
import re
import nltk
import numpy as np

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from collections import Counter

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 2. Download NLTK resources

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("averaged_perceptron_tagger_eng")

data_path = "/content/drive/MyDrive/NLP_lab/IMDB Dataset.csv"

df = pd.read_csv(data_path)

df = df.head(5000)

df = df[["review", "sentiment"]]

df.head()

# 4. Stopwords setup

stop_words = set(stopwords.words("english"))

# keep negation words because they are important for sentiment
negation_words = {"no", "not", "nor", "never"}

stop_words = stop_words - negation_words

# 5. Negation handling

def handle_negation(text):
    text = text.replace("not good", "not_good")
    text = text.replace("not bad", "not_bad")
    text = text.replace("not great", "not_great")
    text = text.replace("not amazing", "not_amazing")
    text = text.replace("not worth", "not_worth")
    text = text.replace("never good", "never_good")
    return text

"""Pre-processing of dataset"""

# 6. Complete preprocessing function

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"<.*?>", " ", text)
    text = handle_negation(text)
    text = re.sub(r"[^a-zA-Z_\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    tokens = word_tokenize(text)

    filtered_tokens = []
    for word in tokens:
        if word not in stop_words:
            filtered_tokens.append(word)

    return filtered_tokens

# 7. Apply preprocessing

df["tokens"] = df["review"].apply(preprocess_text)

df["preprocessed_text"] = df["tokens"].apply(lambda words: " ".join(words))

df[["review", "preprocessed_text", "sentiment"]].head()

# 8. POS tagging

df["pos_tags"] = df["tokens"].apply(nltk.pos_tag)

df[["tokens", "pos_tags"]].head()

# 9. POS tag frequency analysis

all_tags = []

for row in df["pos_tags"]:
    for word, tag in row:
        all_tags.append(tag)

tag_count = Counter(all_tags)

tag_count.most_common(10)

"""TF-IDF feature extraction"""

# 10. Features and labels

X = df["preprocessed_text"]
y = df["sentiment"]

# 11. TF-IDF vectorization with bigrams

tfidf = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2)
)

X_tfidf = tfidf.fit_transform(X)

# 12. Splitting dataset

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""model training and comparison"""

# 13. Logistic Regression

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

# 14. Naive Bayes

nb_model = MultinomialNB()

nb_model.fit(X_train, y_train)

y_pred_nb = nb_model.predict(X_test)

print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

# 15. Support Vector Machine

svm_model = LinearSVC(C=0.1)

svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

"""cross validation"""

# 16. Cross-validation on SVM

scores = cross_val_score(svm_model, X_tfidf, y, cv=5)

print("Cross-validation scores:", scores)
print("Average cross-validation accuracy:", scores.mean())

# 17. Predict sentiment on new unseen review

def predict_sentiment(text):
    tokens = preprocess_text(text)
    cleaned_text = " ".join(tokens)

    text_vec = tfidf.transform([cleaned_text])

    return svm_model.predict(text_vec)[0]

print(predict_sentiment("This movie was fantastic!"))
print(predict_sentiment("This movie was not good."))
print(predict_sentiment("The acting was great but the story was boring."))





df[["review", "preprocessed_text"]].head()

"""Nouns

NN → Noun (singular)
eg. dog, movie

NNS → Noun (plural)
eg. reviewers, movies

NNP → Proper noun (name)
eg. India, Netflix

NNPS → Proper noun (plural)
eg. Americans

Verbs

VB → Base form eg. go, eat

VBD → Past tense
eg. mentioned, watched

VBG → Present participle (-ing)
eg. running, watching

VBN → Past participle
eg. written, eaten

VBP → Present (plural)
eg. they run

VBZ → Present (singular)
eg. he runs

Adjectives

JJ → Adjective
eg. good, amazing

JJR → Comparative
eg. better

JJS → Superlative
eg. best

Adverbs

RB → Adverb
eg. quickly, very

RBR → Comparative
eg. faster

RBS → Superlative
eg. fastest

Others (important ones)

CD → Cardinal number
eg. one, two, 100

DT → Determiner
eg. the, a, an

IN → Preposition
eg. in, on, at

PRP → Pronoun
eg. he, she, they

CC → Conjunction
eg. and, but
"""